print("Bustillos Olivas Fernando")
print("Carrillo Dominguez Aleksa")
print("Mendoza Legarda Omar")
print("Rodríguez Vargas Iván")
print("Sánchez Hernández María Fernanda")
print("Vázquez López Andrea")